### ISSUE TITLE
ERROR: Failed to resolve: com.shimaami.android:kotlinprogressview:1.0.0

### ISSUE THREAD

**Issue by AkhilRaja** [shimaami/AndroidProgressView-Kotlin#1]
Unable to add the implementation of the app.

**Comment by therajanmaurya** [comment]
+1, I can't resolve too.

But Big thanks @shimaami 👏.  I needed exactly this.

**Comment by shimaami** [comment]
@AkhilRaja I'm working on fixing this. Sorry for being late. 
@therajanmaurya You are welcome 😉

**Comment by shimaami** [comment]
implementation 'com.shimaami.android:kotlinprogressview:1.0.0'
<com.shimaami.kotlinprogressview.ProgressView
            android:id="@+id/progressCircle"
            android:layout_width="150dp"
            android:layout_height="150dp"
            android:layout_marginBottom="10dp"
            android:layout_gravity="center_horizontal"
            app:pvDirection="fromLeft"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:pvProgress="0.5"
            app:pvShape="circle"/>
